config/routes.rb
Rails.application.routes.draw do

  root "suggestions#index"

  resources :prefectures, only: [:index] do

  end

  resources :images

  resources :prefectures, only: [:index]

  resources :statuses, only: [:index, :create]
  get "is/:name" => "statuses#result"

  resources :suggestions

  resources :names, only: [] do
    collection do
      get "suggestion"
    end
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    count = params["count"]
    @images = Image.all.shuffle.first(count.to_i)
  end

end

app/controllers/names_controller.rb
# -*- coding: utf-8 -*-
require 'rakuten_web_service'

class NamesController < ApplicationController
  #before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestion
  # GET /suggestion.json
  def suggestion
    #render json: {keyword: suggestion_params.join("")}

    #str = Iiname::Engine.new(params).fetch(mode: "Book", suggestion_params.join(" "))
    #str = Iiname::Engine.new.search_by_webapi(suggestion_params.join(" "))
    #str = Iiname::Engine.new(:keyword => suggestion_params.join(" ")).fetch(mode: "Book")
    str = Iiname::Engine.new(:keyword => suggestion_params.join(" "), mode: :book).fetch.first
    render json: {keyword: str}
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:names)
    end
end

app/controllers/prefectures_controller.rb
# coding: utf-8
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: []

  # GET /prefectures
  # GET /prefectures.json
  def index
    @prefectures = Prefecture.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      params.require(:id, :name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prefecture_params
      params.require(:id)
    end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # POST /statuses
  def create
    @status = Status.new(keyword: params[:keyword])
      if @status.save
        redirect_to '/is/'+CGI.escape(params[:keyword])
      else
        redirect_to root_path
      end
  end

  def result
    @name = params[:name]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:keyword)
    end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  #before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all
    @prefectures = Prefecture.all
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    if params["interests"].present?
      keyword = params["interests"]
      #render json: {keyword: keyword} and return
      ignite_engine(keyword) and return
    end

    if params["prefecture_id"].present?
      hokkaido = ["夕張メロン","白い恋人"]
      tokyo = ["東京タワー","東京バナナ"]
      other = ["その他","北海道と東京以外です"]

      case params["prefecture_id"]
      when "1"
        keyword = hokkaido.sample
      when "13"
        keyword = tokyo.sample
      else
        keyword = other.sample
      end

      #render json: {keyword: keyword} and return
      ignite_engine(keyword) and return
    end

    if params[:places].present? && params[:places].kind_of?(Array)
      ignite_engine(params[:places].join, true) and return
    end

    if params[:names].present? and params[:names].kind_of?(Array)
      origin_keyword = params[:names].join(" ")
      ignite_engine(params[:names].join, false, :book) and return
    end

    unless @suggestion.present?
      index = Random.rand(0..Suggestion.all.length - 1)
      origin_keyword = Suggestion.all[index].keyword

      ignite_engine(origin_keyword)
    end
  end

  def ignite_engine(origin_keyword, skip_search=false, m = :web)
    morph_target = origin_keyword
    searched_keyword = ""
    unless skip_search
      search_results = Iiname::Engine.new(keyword: origin_keyword, mode: m).fetch
      searched_keyword = search_results.sample.title.slice(0..19)
      morph_target = searched_keyword
    end
    nouns = MorphologicalAnalyser.new.extract_noun(morph_target)
    nouns = nouns.sample(Random.rand(1..3))
    puts("origin_keyword = #{origin_keyword}")
    puts("searched_keyword = #{searched_keyword}")
    puts("nouns = #{nouns}")
    render json: {keyword: nouns.shuffle.join, searched: searched_keyword, origin: origin_keyword}
  end


  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_suggestion
    #   @suggestion = Suggestion.find(params[:id])
    # end
    #
    # # Never trust parameters from the scary internet, only allow the white list through.
    # def suggestion_params
    #   params.require(:suggestion).permit(:keyword)
    # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="iiname" class="<%= 'feature-toggle-disabled' if Rails.env.production? %>">
  <head>
    <title>いいね～む</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="http://maps.google.com/maps/api/js?sensor=true&language=ja&libraries=places"></script>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="/slick.css">
    <link rel="stylesheet" href="/slick-theme.css">

    <script type="text/javascript">
      $(document).ready(function(){
        $('.question_slider').slick({
        autoplay:false,
        dots:true,
        slidesToShow:1,
        slidesToScroll:1,
        draggable: false,
        });
      });
      $(window).scroll(function(){
        var now = $(window).scrollTop();
        if( now > 500 ){
          $('#page-top').fadeIn('slow') ;
        }else {
          $('#page-top').fadeOut('slow');
        }
      });
      function movepagetop() {
        var x1 = x2 = x3 = 0;
        var y1 = y2 = y3 = 0;
        if (document.documentElement) {
          x1 = document.documentElement.scrollLeft || 0;
          y1 = document.documentElement.scrollTop || 0;
        }
        if (document.body) {
          x2 = document.body.scrollLeft || 0;
          y2 = document.body.scrollTop || 0;
        }
          x3 = window.scrollX || 0;
          y3 = window.scrollY || 0;
        var x = Math.max(x1, Math.max(x2, x3));
        var y = Math.max(y1, Math.max(y2, y3));
        window.scrollTo(Math.floor(x / 2), Math.floor(y / 2));
        if (x > 0 || y > 0) {
          window.setTimeout("movepagetop()", 25);
        }
      }
    </script>
  </head>
  <body>
    <div class="container">
      <header>
        <div class="row">
          <div class="col-xs-10 logo">
            <a href="<%= root_path %>"><img src="<%= asset_path "logo.gif" %>"></a>
          </div>
          <div class="col-xs-2 icon">
            <a rel="leanModal" href="#modal-window"><img src="<%= asset_path "question.gif" %>"></a>
          </div>
        </div>
      </header>
      <div class="row">
        <div class="col-md-12 notice_wrapper">
          <div class="black_line"></div>
          <p id="notice"><%= notice %></p>
        </div>
      </div>
      <%= yield %>
      <footer class="footer">
        <div class="row">
          <div class="col-md-12">
            <div class="black_line"></div>
            <p>&copy; Team iine, Advanced Institute of Industrial Technology, enPiT BizApp, 2015</p>
          </div>
        </div>
      </footer>
    </div>
    <div id="page-top" class="page-top">
      <p><a id="move-page-top" class="move-page-top" onclick="movepagetop(); return false">▲</a></p>
    </div>
    <div id="modal-window" style="display:none;">
      <center><strong>チーム名ブレインストーミングツール　いいねーむ</strong></center>
      <p style="margin-bottom:1em;"></p>
      <div align="center">
        <ul>
          <li>「いいね～む」はチーム名ブレインストーミングツールです。</li>
          <li>10秒毎に一つ、チーム名の提案をします。</li>
          <li>質問に答えると、チーム名に反映されます。</li>
          <li>付箋をクリックすると、使用するチーム名を決定します。</li>
          <li>チーム名を決定すると、ツイッターでつぶやくことができます。</li>
        </ul>
      </div>
      <p style="margin-bottom:2em;"><center><B>免責事項</B></center></p>
        <div align="left">
          <ul>
          <li>当ウェブサイトに掲載された情報を利用された結果、生ずる損害について、一切の責任を負いかねます。</li>
          <li>当ウェブサイトの掲載内容は所属する団体の意見を代表するものではありません。</li>
          </ul>
        </div>
      <p style="margin-bottom:2em;"><center><B>アンケートのお願い</B></center></p>
        <div align="left">
          <ul>
            <li>この度はチーム名ブレインストーミングツール「いいね～む」にアクセスして頂き誠にありがとうございます。</li>
            <li>当ウェブサイトをもっと使いやすいものにする為、是非以下のアンケートへのご協力をお願い致します。</li>
          </ul>
        </div>
       <div style="margin-bottom:2em;">
         <p>
          <div align="right">
            <center><a href="http://goo.gl/forms/o3UmwG6kMT" target="_blank" >アンケートに回答する</a></center>
          </div>
         </p>
        </div>
      <div class="modal_close"><center><p style="margin-bottom:1em;"><%= link_to "閉じる" %></center></p></div>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-71059650-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/prefectures/index.html.erb
<div ng-controller="MainController as vm" ng-cloak>
  <div class="row">
    <div class="suggestion col-md-12">
      <p class="lead">あなたのチーム名は</p>
      <a href="/statuses?keyword={{vm.keyword}}"  class="confirm" data-method="post">
        <div id="highest_suggestion" ng-bind="vm.keyword"></div></a>
      <p class="lead">です。</p>
    </div>
    <script>
    $('.confirm').click(function() {
    if (!confirm('このチーム名を使用しますか？')) {
    return false;
    }
    });
    </script>
    <h1>Listing Prefectures</h1>
    <form action=""method="post">
      <p>出身地はどこですか？</p>
      <p>
      <select>
      <% @prefectures.each do | prefecture | %>
      <option value="<%= prefecture.id %>"><%= prefecture.prefecture %></option>
      <% end %>
      </select>
      </p>
    </form>
    <div class="list col-md-12">
      <ul id="list" class="list-unstyled" ng-repeat="element in vm.list | orderBy:'$index':true track by $index">
        <li>{{element}}</li>
      </ul>
    </div>
  </div>
</div>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>最近使用されたキーワード</th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.keyword %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statuses/result.erb
<div class="row">
  <div class="result col-md-12">
      <p class="result_text">私たちのチーム名は<br />
      <%= CGI.unescape(@name) %><br />
      です！<h2>
  </div>
</div>
<div class="row">
  <div class="result_ui col-md-12">
    <ul class="social_buttons">
      <li>  <!-- tweetボタン -->
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= root_url %>is/<%= CGI.escape(@name) %>" data-text="いいね〜むから、チーム名『 <%= CGI.unescape(@name) %> 』が提案されました。" data-count="none" data-size="large" data-hashtags="iiname">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </li>
    </ul>
    TweetボタンをクリックするとTwitterでこのチーム名を紹介することが出来ます
  </div>
</div>

app/views/suggestions/index.html.erb
<div ng-controller="MainController as vm" ng-cloak>
  <div class="question_slider">
    <div><div ng-include="'partials/place.html'"></div></div>
    <div><div ng-include="'partials/interests.html'"></div></div>
    <div><div ng-include="'partials/names.html'"></div></div>
  </div>
  <div class="row">
    <div class="suggestion col-md-12">
      <div class="black_line"></div>
      <div class="sticky_margin">
        <div class="sticky_wrapper">
          <a href="/statuses?keyword={{vm.keyword.word}}" data-method="post">
            <div class="sticky new_sticky {{vm.keyword.className}}">
                  <span id="highest_suggestion" ng-bind="vm.keyword.word" class="name"></span>
                  <span id="highest_suggestion_uniqueness" ng-bind="vm.uniqueness"></span>
                  <span class="origin">
                    <span ng-if="vm.keyword.origin != null">元となった解答 : "</span>
                    <img ng-if="vm.keyword.className == 'interests'" ng-src="{{vm.keyword.origin}}" />
                    <span ng-if="vm.keyword.className != 'interests'" ng-bind="vm.keyword.origin"></span>
                    <span ng-if="vm.keyword.origin != null">"</span>
                  </span>
            </div>
          </a>
        </div>
      </div>
    </div>
    <div class="list col-md-12">
      <ul id="list" class="list-unstyled" ng-repeat="element in vm.list | orderBy:'$index':true track by $index">
        <li>
          <div class="sticky_margin">
            <div class="sticky_wrapper">
              <a href="/statuses?keyword={{element.word}}" data-method="post">
                <div class="sticky {{element.className}}">
                  <span class="name" ng-bind="element.word"></span>
                  <span class="origin">
                    <span ng-if="element.origin != null">元となった解答 : "</span>
                    <img ng-if="element.className == 'interests'" ng-src="{{element.origin}}" />
                    <span ng-if="element.className != 'interests'" ng-bind="element.origin"></span>
                    <span ng-if="element.origin != null">"</span>
                  </span>
                </div>
              </a>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @suggestion.keyword %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>

app/views/welcome/index.html.erb
<h1>hello</h1>